export const TRAFFIC_GROWTH_ENTRIES_2026_05_02 = [
  {
    name: "Mastra",
    category: "Infrastructure",
    subcategory: "Hosting & Frameworks",
    url: "https://github.com/mastra-ai/mastra",
    source_url: "https://github.com/mastra-ai/mastra",
    description: "TypeScript framework for building AI agents, workflows, RAG, evals, and production-ready agent apps.",
    stage: "Live",
    model: "Open-source + cloud",
    traction: "Active OSS project",
    earn_potential: "Enables sellable agent apps",
    difficulty: "Medium",
    time_to_first_dollar: "1–2 weeks",
    votes_up: 46,
    votes_down: 0,
    agent_native: 1,
  },
  {
    name: "Agno",
    category: "Infrastructure",
    subcategory: "Hosting & Frameworks",
    url: "https://github.com/agno-agi/agno",
    source_url: "https://github.com/agno-agi/agno",
    description: "Runtime for production agentic software with sessions, tracing, scheduling, RBAC, teams, and workflows.",
    stage: "Live",
    model: "Open-source + platform",
    traction: "Active OSS project",
    earn_potential: "Enables managed agent services",
    difficulty: "Medium",
    time_to_first_dollar: "1–2 weeks",
    votes_up: 44,
    votes_down: 0,
    agent_native: 1,
  },
  {
    name: "Pydantic AI",
    category: "Infrastructure",
    subcategory: "Hosting & Frameworks",
    url: "https://pydantic.dev/docs/ai/overview/",
    source_url: "https://pydantic.dev/docs/ai/overview/",
    description: "Python agent framework from Pydantic for building production-grade GenAI apps with typed validation.",
    stage: "Live",
    model: "Open-source",
    traction: "Pydantic ecosystem",
    earn_potential: "Enables reliable AI services",
    difficulty: "Medium",
    time_to_first_dollar: "1–2 weeks",
    votes_up: 42,
    votes_down: 0,
    agent_native: 1,
  },
  {
    name: "OpenAI Agents SDK",
    category: "Infrastructure",
    subcategory: "Hosting & Frameworks",
    url: "https://openai.github.io/openai-agents-python/",
    source_url: "https://openai.github.io/openai-agents-python/",
    description: "Lightweight SDK for agentic apps with tools, handoffs, guardrails, tracing, and Swarm-style primitives.",
    stage: "Live",
    model: "Open-source SDK",
    traction: "Official OpenAI SDK",
    earn_potential: "Enables OpenAI-native agents",
    difficulty: "Medium",
    time_to_first_dollar: "1–2 weeks",
    votes_up: 58,
    votes_down: 0,
    agent_native: 1,
  },
  {
    name: "Coinbase AgentKit",
    category: "Infrastructure",
    subcategory: "Payment Rails",
    url: "https://github.com/coinbase/agentkit",
    source_url: "https://github.com/coinbase/agentkit",
    description: "Coinbase toolkit that gives AI agents crypto wallets and onchain actions across supported frameworks.",
    stage: "Live",
    model: "Open-source + Coinbase services",
    traction: "Coinbase Developer Platform",
    earn_potential: "Agent wallets + onchain payments",
    difficulty: "Medium",
    time_to_first_dollar: "< 1 week",
    votes_up: 77,
    votes_down: 0,
    agent_native: 1,
  },
  {
    name: "Cloudflare Agents SDK",
    category: "Infrastructure",
    subcategory: "Hosting & Frameworks",
    url: "https://developers.cloudflare.com/agents/",
    source_url: "https://developers.cloudflare.com/agents/",
    description: "Build stateful AI agents on Cloudflare with persistent memory, WebSockets, and scheduled tasks.",
    stage: "Live",
    model: "Cloudflare usage-based",
    traction: "Cloudflare developer platform",
    earn_potential: "Deploy paid agent services",
    difficulty: "Medium",
    time_to_first_dollar: "1–2 weeks",
    votes_up: 61,
    votes_down: 0,
    agent_native: 1,
  },
  {
    name: "Browserbase Stagehand",
    category: "Infrastructure",
    subcategory: "Agent Tools",
    url: "https://docs.browserbase.com/welcome/quickstarts/stagehand.md",
    source_url: "https://docs.browserbase.com/welcome/quickstarts/stagehand.md",
    description: "Browser automation toolkit for web agents that mixes code with natural-language browser actions.",
    stage: "Live",
    model: "Open-source + hosted browsers",
    traction: "Browserbase ecosystem",
    earn_potential: "Automate paid web workflows",
    difficulty: "Medium",
    time_to_first_dollar: "< 1 week",
    votes_up: 49,
    votes_down: 0,
    agent_native: 1,
  },
  {
    name: "Arcade.dev",
    category: "Infrastructure",
    subcategory: "Agent Tools",
    url: "https://docs.arcade.dev/en/home",
    source_url: "https://docs.arcade.dev/en/home",
    description: "Auth providers, MCP servers, and tool-calling infrastructure for agents that need real user permissions.",
    stage: "Live",
    model: "Developer platform",
    traction: "MCP + agent tooling",
    earn_potential: "Power authenticated agent products",
    difficulty: "Medium",
    time_to_first_dollar: "1–2 weeks",
    votes_up: 39,
    votes_down: 0,
    agent_native: 1,
  },
  {
    name: "E2B",
    category: "Infrastructure",
    subcategory: "Agent Tools",
    url: "https://e2b.dev/",
    source_url: "https://e2b.dev/",
    description: "Secure cloud sandboxes for AI agents that need code execution, computer use, and real-world tools.",
    stage: "Live",
    model: "Usage-based cloud",
    traction: "Agent sandbox platform",
    earn_potential: "Run paid coding/research agents",
    difficulty: "Medium",
    time_to_first_dollar: "1–2 weeks",
    votes_up: 53,
    votes_down: 0,
    agent_native: 1,
  },
  {
    name: "Vercel AI SDK",
    category: "Infrastructure",
    subcategory: "Hosting & Frameworks",
    url: "https://ai-sdk.dev/docs/introduction",
    source_url: "https://ai-sdk.dev/docs/introduction",
    description: "TypeScript toolkit for building AI-powered apps and agents across React, Next.js, Node, and more.",
    stage: "Live",
    model: "Open-source + Vercel platform",
    traction: "Vercel ecosystem",
    earn_potential: "Ship monetized AI apps fast",
    difficulty: "Easy",
    time_to_first_dollar: "< 1 week",
    votes_up: 65,
    votes_down: 0,
    agent_native: 1,
  },
] as const;
